name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL || 'default-value' }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY || 'default-value' }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || 'default-value' }}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ vars.NEXT_PUBLIC_CLERK_SIGN_IN_URL || 'default-value' }}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ vars.NEXT_PUBLIC_CLERK_SIGN_UP_URL || 'default-value' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
